version: '3.8'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

  database:
    depends_on:
      - db
    image: database:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      DATABASE_DB_HOST: db:3306
      DATABASE_DB_USER: user
      DATABASE_DB_PASSWORD: 1234
      DATABASE_DB_NAME: database
